{
 "title": "NixOS server",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Qbit Firewalled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qbittorrent_connected{server=\"127.0.0.1:8080\",job=\"qbittorrent_exporter\"} - qbittorrent_firewalled{server=\"127.0.0.1:8080\",job=\"qbittorrent_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used space",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * ((node_filesystem_size_bytes{mountpoint=~\"/$|/nix$|/var$|/boot$|/bigpool/media$\"} -\n  node_filesystem_free_bytes{mountpoint=~\"/$|/nix$|/var$|/boot$|/bigpool/media$\"} \n  )/ \n  node_filesystem_size_bytes{mountpoint=~\"/$|/nix$|/var$|/boot$|/bigpool/media$\"}\n)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Real RAM usage excluding cache and reclaimable memory",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"localhost:9100\", job=\"node\"} / node_memory_MemTotal_bytes{instance=\"localhost:9100\", job=\"node\"})) * 100"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Overall CPU busy percentage (averaged across all cores over 10min)",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"localhost:9100\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Services KO",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name!~\"acme.*\", state=\"failed\", name=~\".*service\"} == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Qbittorrent Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "qbittorrent_up{server=\"127.0.0.1:8080\", job=\"qbittorrent_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMART STATUS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 13, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "smartctl_device_smart_status", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "Wiser Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(ping_loss_ratio{target=\"192.168.1.107\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "Zpool Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "zfs_pool_health", "legendFormat": "{{pool}}" }
   ]
  },
  {
   "title": "Espace Libre",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=~\"/|/bigpool/media|/nix|/var\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "smartctl_device_temperature", "legendFormat": "{{device}}" }
   ]
  }
 ]
}